# Model inspection <a class="tocSkip">
> After generating a model we inspect it here to find its flaws.

In [ ]:
#default_exp inspection

In [ ]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [ ]:
#export
import pandas as pd
from fastai2.tabular.all import *
from fastai2 import metrics
from sklearn import ensemble
import pickle
from src.utils import *
from src.preprocessing import *
from src.modelling import *
from typing import List
import matplotlib.pyplot as plt

In [ ]:
with open(model_data_path, "rb") as f:
    to = pickle.load(f)

In [ ]:
dls = to.dataloaders()

In [ ]:
#hide
dls.show_batch()

In [ ]:
loss_fun = torch.nn.functional.mse_loss
learn = tabular_learner(dls, n_out=1, loss_func=loss_fun, config=dict(active_fun=Mish))

In [ ]:
learn.load("model-final")

In [ ]:
df_s = pd.read_csv(clean_data_path, encoding="utf8")

## Feature importance

In [ ]:
dls.valid.xs

Id  MSSubClass  MSZoning  LotFrontage  Street  Alley  LotShape  \
80   0           8         2            0       1      0         4   
81   0           1         2           21       1      0         4   
82   0           6         2           17       1      0         4   
83   0           2         3           11       1      0         4   
84   0           1         2            0       1      0         4   
85   0           2         2            0       1      0         4   
86   0           8         2            0       1      0         1   
87   0           1         2           23       1      0         4   
88   0          10         3            3       1      0         4   
89   0           4         2            0       1      0         4   
90   0           4         3           11       1      0         4   
91   0           9         3           21       1      0         4   
92   0           1         2            0       1      0         1   
93   0          10         3            0       1      0         4   
94   0           1         2            0       1      0         4   
95   0           5         2           15       1      0         2   
96   0           1         2           11       1      0         1   
97   0           4         2           17       1      0         4   
98   0           1         2            0       1      0         1   
99   0           1         2           17       1      0         4   

    LandContour  Utilities  LotConfig  ...  BsmtFinSF2  BsmtUnfSF  \
80            3          1          4  ...   -0.219295  -0.351932   
81            3          1          4  ...   -0.219295  -0.630575   
82            3          1          4  ...   -0.219295   0.495607   
83            3          1          4  ...   -0.219295   0.381828   
84            3          1          4  ...   -0.219295   0.193744   
85            3          1          4  ...   -0.219295   0.637250   
86            3          1          2  ...   -0.219295   1.417450   
87            0          1          4  ...   -0.219295  -0.235831   
88            3          1          3  ...   -0.219295  -0.516795   
89            3          1          1  ...    1.419566  -0.282271   
90            3          1          4  ...   -0.219295   0.363252   
91            3          1          4  ...   -0.219295  -1.257521   
92            3          1          1  ...   -0.219295   2.320717   
93            3          1          3  ...   -0.219295  -0.465711   
94            3          1          4  ...   -0.219295  -0.231186   
95            0          1          3  ...   -0.219295  -0.967268   
96            3          1          4  ...   -0.219295  -0.881353   
97            3          1          4  ...   -0.219295  -0.430880   
98            2          1          4  ...   -0.219295  -0.663083   
99            3          1          4  ...   -0.219295   1.076113   

    TotalBsmtSF  1stFlrSF  2ndFlrSF  GrLivArea  GarageYrBlt  GarageArea  \
80    -0.147713 -0.538062 -0.699373  -1.127443    -0.005901   -0.696164   
81     1.229569  1.189541 -0.699373   0.371898     1.363213    1.039508   
82    -0.659466 -1.179982  1.357005   0.144212    -1.752702   -0.863458   
83     0.114838 -0.208729 -0.699373  -0.841623    -0.053112   -0.110636   
84     1.472096  1.493756 -0.699373   0.635918     1.268791    2.064182   
85    -0.523740  0.664841 -0.699373  -0.083475     1.410424    0.600362   
86     1.398670  1.524456 -0.699373   0.662562    -0.478010    0.098481   
87    -0.203338 -0.607836 -0.699373  -1.187998    -0.572431   -0.152459   
88     0.366265  0.106649 -0.699373  -0.567915     0.985526   -0.309297   
89    -0.470340 -0.942751  0.755072  -0.185207    -0.478010   -0.643885   
90    -0.786291 -1.093462  0.362862  -0.664803     1.032737    0.851303   
91    -2.339350  0.391327  0.891256   1.093714     0.041309    0.406929   
92     1.089394  1.013711 -0.699373   0.219300     1.127159    1.996219   
93     0.384065  0.128977 -0.6993

In [ ]:
def get_df_preds(df:pd.DataFrame, learn:Learner, cat_names:List[str], cont_names:List[str]):
    "`df` is the `TabularPandas.valid.xs` attribute"
    x_cat = torch.from_numpy(df[cat_names].values).long()
    x_cont = torch.from_numpy(df[cont_names].values).float()
    learn.model.eval()
    return learn.model.forward(x_cat, x_cont)

In [ ]:
%%time
get_df_preds(to.valid.xs, learn, to.cat_names, to.cont_names)

CPU times: user 15.6 ms, sys: 0 ns, total: 15.6 ms
Wall time: 9.14 ms


tensor([[10.2952],
        [11.1078],
        [11.5308],
        [ 8.7183],
        [11.1293],
        [12.4043],
        [ 7.8074],
        [10.0069],
        [ 5.1600],
        [11.6227],
        [10.9821],
        [ 7.3126],
        [12.2341],
        [ 9.7876],
        [ 9.0370],
        [13.0619],
        [10.4402],
        [10.5533],
        [ 9.8991],
        [10.1030]], grad_fn=<AddmmBackward>)

In [ ]:
%%time
learn.get_preds(dl=dls.valid)

CPU times: user 78.1 ms, sys: 0 ns, total: 78.1 ms
Wall time: 33.7 ms


(tensor([[10.2952],
         [11.1078],
         [11.5308],
         [ 8.7183],
         [11.1293],
         [12.4043],
         [ 7.8074],
         [10.0069],
         [ 5.1600],
         [11.6227],
         [10.9821],
         [ 7.3126],
         [12.2341],
         [ 9.7876],
         [ 9.0370],
         [13.0619],
         [10.4402],
         [10.5533],
         [ 9.8991],
         [10.1030]]),
 tensor([[11.9177],
         [12.3014],
         [11.5899],
         [11.6128],
         [12.5242],
         [11.6263],
         [12.1955],
         [11.4590],
         [12.0076],
         [11.5617],
         [11.8123],
         [11.6263],
         [12.2308],
         [12.0137],
         [12.8610],
         [12.0725],
         [11.6656],
         [11.5617],
         [12.4684],
         [11.6527]]))

In [ ]:
def get_feature_importance(to:TabularPandas, learn:Learner):
    feature_losses = {}
    
    ref_loss = learn.loss_func(*learn.get_preds()).item()
    ys = torch.from_numpy(to.valid.ys.values).float()
    for col in to.valid.xs.columns:
        vals = to.valid.xs[col].values
        xs = to.valid.xs.copy()
        xs[col] = np.random.choice(vals)
        
        _ys = get_df_preds(xs, learn, to.cat_names, to.cont_names)
        
        feature_losses[col] = learn.loss_func(_ys, ys).item()
    
    return feature_losses, ref_loss

In [ ]:
%%time
importances, ref_loss = get_feature_importance(to, learn)

CPU times: user 3.31 s, sys: 78.1 ms, total: 3.39 s
Wall time: 865 ms


In [ ]:
# fig, ax = plt.subplots()
# ax.bar()
# plt.show()
losses = pd.DataFrame(importances.items(), columns=["column", "loss"])
losses["loss Δ"] = losses["loss"] - ref_loss

losses.sort_values("loss Δ", ascending=False, inplace=True)
display_all(losses)

column       loss    loss Δ
11     Neighborhood  10.169829  3.438626
12       Condition1   8.758464  2.027260
92      OpenPorchSF   7.755461  1.024258
15       HouseStyle   7.655418  0.924214
44     TotRmsAbvGrd   7.640514  0.909311
50       GarageCars   7.429509  0.698305
30       BsmtFinSF1   7.383034  0.651830
21      Exterior2nd   7.349138  0.617935
20      Exterior1st   7.137808  0.406604
62           MoSold   7.105027  0.373823
89      GarageYrBlt   7.082514  0.351311
84        BsmtUnfSF   7.069096  0.337893
53       PavedDrive   7.067500  0.336296
47      FireplaceQu   7.055572  0.324368
27         BsmtCond   7.027484  0.296280
22       MasVnrType   6.998999  0.267796
52       GarageCond   6.981701  0.250498
40         HalfBath   6.935542  0.204339
82       MasVnrArea   6.913500  0.182297
35       Electrical   6.889196  0.157993
87         2ndFlrSF   6.889026  0.157822
88        GrLivArea   6.853298  0.122095
16      OverallQual   6.831486  0.100282
51       GarageQual   6.827278  0.096074
80        YearBuilt   6.791422  0.060219
85      TotalBsmtSF   6.787231  0.056028
48       GarageType   6.778928  0.047724
54    EnclosedPorch   6.777542  0.046339
38     BsmtHalfBath   6.754882  0.023679
49     GarageFinish   6.749893  0.018689
83       BsmtFinSF2   6.733849  0.002645
67  YearRemodAdd_na   6.731204  0.000000
66     YearBuilt_na   6.731204  0.000000
78   OpenPorchSF_na   6.731204  0.000000
77    WoodDeckSF_na   6.731204  0.000000
76    GarageArea_na   6.731204  0.000000
75   GarageYrBlt_na   6.731204  0.000000
74     GrLivArea_na   6.731204  0.000000
73      2ndFlrSF_na   6.731204  0.000000
55        3SsnPorch   6.731204  0.000000
72      1stFlrSF_na   6.731204  0.000000
57         PoolArea   6.731204  0.000000
71   TotalBsmtSF_na   6.731204  0.000000
58           PoolQC   6.731204  0.000000
60      MiscFeature   6.731204  0.000000
69    BsmtFinSF2_na   6.731204  0.000000
61          MiscVal   6.731204  0.000000
68    MasVnrArea_na   6.731204  0.000000
65       LotArea_na   6.731204  0.000000
70     BsmtUnfSF_na   6.731204  0.000000
0                Id   6.731204  0.000000
5             Alley   6.731204  0.000000
4            Street   6.731204  0.000000
45       Functional   6.731204  0.000000
32          Heating   6.731204  0.000000
19         RoofMatl   6.731204  0.000000
34       CentralAir   6.731204  0.000000
36     LowQualFinSF   6.731204  0.000000
8         Utilities   6.731204  0.000000
9         LotConfig   6.701438 -0.029765
56      ScreenPorch   6.699945 -0.031258
24        ExterCond   6.671610 -0.059594
18        RoofStyle   6.668730 -0.062473
63         SaleType   6.661635 -0.069569
86         1stFlrSF   6.660796 -0.070408
79          LotArea   6.649301 -0.081903
28     BsmtExposure   6.635768 -0.095435
90       GarageArea   6.603226 -0.127977
6          LotShape   6.598673 -0.132531
91       WoodDeckSF   6.565967 -0.165236
64    SaleCondition   6.553056 -0.178147
13       Condition2   6.546261 -0.184943
26         BsmtQual   6.522632 -0.208572
31     BsmtFinType2   6.450871 -0.280333
10        LandSlope   6.450739 -0.280465
2          MSZoning   6.423635 -0.307569
81     YearRemodAdd   6.376345 -0.354859
59            Fence   6.337615 -0.393589
46       Fireplaces   6.308576 -0.422628
39         FullBath   6.287035 -0.444168
33        HeatingQC   6.154579 -0.576624
42     KitchenAbvGr   6.113367 -0.617836
17      OverallCond   5.904809 -0.826394
3       LotFrontage   5.763091 -0.968112
23        ExterQual   5.739613 -0.991591
7       LandContour   5.699353 -1.031851
29     BsmtFinType1   5.675032 -1.056171
25       Foundation   5.606566 -1.124638
37     BsmtFullBath   5.497362 -1.233841
1        MSSubClass   5.478582 -1.252621
43      KitchenQual   5.372377 -1.358826
41     BedroomAbvGr   5.173593 -1.557611
14         BldgType   5.137650 -1.593554